relayer/chains/sui/client/client.go, relayer/chains/sui/config.go, relayer/chains/sui/keys.go, relayer/chains/sui/keys_test.go, relayer/chains/sui/provider.go, relayer/chains/sui/provider_test.go, relayer/chains/sui/query.go, relayer/chains/sui/types/types.go
Added keystore implementation to import/restore or create new sui key in centralized relay. Added function to get the balance of the configured accounts in mist.
Supported only ed25519 keystores for sui similar to sui wallets.
Importing keystore will import only the first account in the keystore
=> feat: added keystore implementation in centralized-relay for sui keystore

relayer/chains/evm/client.go, relayer/chains/evm/listener.go, relayer/chains/evm/provider.go, relayer/chains/evm/route.go
This pull request fixes the issue with waiting for a block to be mined by using the `WaitForTransactionMined` method instead of polling. It also refactors the `GetConcurrency` method to use the `runtime.NumCPU` function to determine the concurrency level.
=> fix: wait for block mined instead of poll

relayer/chains/wasm/provider.go
This pull request fixes an import issue in the `relayer/chains/wasm/provider.go` file. The import statement `coretypes` has been changed to `coreTypes` to match the correct package name.
=> Fix import issue

relayer/chains/evm/provider.go, relayer/chains/evm/route.go, relayer/chains/icon/provider.go, relayer/chains/icon/route.go, relayer/chains/wasm/config.go
This pull request adds the ability to adjust the gas and step values from the configuration file for the EVM and ICON chains. Previously, these values were hardcoded, but now they can be customized by modifying the configuration file. This provides more flexibility and allows for better optimization of gas and step usage.
=> Add gas/step adjustment from config

.goreleaser.yaml, Makefile
This pull request updates the cosmwasm version to v2.0.1 for bug fixes and improvements. It also updates the go-releaser version to v1.22.3.
=> Update cosmwasm and go-releaser versions

relayer/chains/evm/provider.go
This pull request fixes an issue where the wrong parameter was being used for estimating gas in the `Provider` struct. The `reqID` parameter has been updated to use `message.ReqID` instead of `message.Sn`.
=> Fix executeCall estimation parameter

CHANGELOG.md, relayer/chains/evm/listener.go, relayer/chains/evm/provider.go, relayer/chains/icon/listener.go, relayer/chains/icon/provider.go, relayer/chains/wasm/provider.go, relayer/provider/provider.go, relayer/relay.go, relayer/types/types.go
This pull request adds a fallback mechanism to switch to polling when the RPC fails. This ensures that the application can continue functioning even if the RPC connection is lost.
=> fix: fallback to polling when RPC fails

relayer/chains/evm/client.go, relayer/chains/evm/provider.go
This pull request refactors the code to use a custom method for handling transaction results. It also includes changes to the `DefaultMinedTimeout` and `DefaultPollingInterval` constants.
Trans. are mostly stuck at tx result polling. And offical sdk method is very aggresive. 
https://github.com/ethereum/go-ethereum/blob/35b2d07f4bf735958b41cd141a5feda5e61be73e/accounts/abi/bind/util.go#L32
=> refactor: transaction result handling

CHANGELOG.md
This pull request adds the changelog entry for version 1.2.7. It includes fixes for using an on/off switch for polling and subscriptions for recoveries, as well as other improvements and bug fixes. Additionally, it changes the Evm block mined to a custom function.
=> Add changelog for version 1.2.7

example/configs/sui.json, relayer/chains/sui/config.go, relayer/chains/sui/listener.go, relayer/chains/sui/provider.go, relayer/chains/sui/provider_test.go, relayer/chains/sui/tx.go, relayer/chains/sui/types/types.go, relayer/relay.go
- Added centralized connection cap and ID in sui contract calls to allow messages only from specific connection id.
- Removed implementations of contract calls: set_admin and revert_message, because these are not needed in case of sui.
- Added support for event listener from multiple xcall packages because on every package upgrade in SUI new packageID is created and if new event is added in the upgrade we need to listen to that package id as well.
=> feat: add connection

relayer/chains/evm/client.go, relayer/chains/evm/listener.go, relayer/chains/icon/client.go, relayer/chains/icon/listener.go, relayer/relay.go
Icon goes back to last saved height for ws error instead of progress interval.
EVM now uses http rpc to mitigate ws connection failures
=> fix: icon ws error and use plain http rpc

CHANGELOG.md, relayer/chains/evm/listener.go
This pull request fixes an issue where the latest height was not being queried correctly when subscription errors occurred. The `resetFunc` function has been replaced with a `resetChannel` to handle the reconnection logic. This ensures that the latest height is correctly retrieved and the subscription is restarted when errors occur.
=> fix: query latest height when subscription errors occur

relayer/chains/evm/client.go
This pull request fixes an issue where a recovered connection was being closed. The `newClient` function was modified to remove the line that closes the connection. Additionally, the `Reconnect` method was updated to close the connection before reconnecting. This ensures that the connection is properly handled and avoids any potential issues with closing a recovered connection.
=> fix: issue with closing recovered connection

relayer/chains/icon/route.go, relayer/chains/wasm/provider.go, relayer/chains/wasm/types/types.go
This pull request fixes an issue where an error was not being returned for relay handle failed. The `WaitForTxResult` function now returns an error if the callback is nil. Additionally, the function now returns the error if the transaction status is not 1. This ensures that errors are properly handled and returned in the relay process.
=> fix: return error for relay handeFailed

relayer/chains/evm/listener.go
The EVM listener was not properly handling connection errors. This pull request fixes the issue by adding proper error handling and reconnecting to the client when a connection error occurs.
Previously we reconnected in any kinds of errors which was unnecessary and lead to hanging connection for a while until another errors occurs. Which kind of fixes by itself but takes very longer resulting longer time for messages deliveries.
In this fixes we check for tcp errors and unresponsive rpc client.
=> fix: connection error handling in EVM listener

CHANGELOG.md, relayer/chains/evm/client.go, relayer/chains/evm/listener.go
This pull request includes fixes for TCP connection errors and improvements in error handling. The changes cover all TCP error scenarios and ensure that the connection is not closed when errors are encountered. Additionally, unnecessary code for closing the connection has been removed.
The client close seems cause issue, the client is interface to pointer and would close recovered connection.
=> fix: TCP connection errors and improve error handling

CHANGELOG.md, relayer/chains/evm/client.go
This pull request changes the usage of the websocket filterLogs `eth_getLogs` for the evm chain to use rpc instead.
=> rf: use rpc for maximum reliability

relayer/chains/wasm/keys.go
We already have lock in place when restoring so removing from `RestoreKeystore()` fixes the issue.
=> remove: SDK context lock from `RestoreKeyStore()`

relayer/chains/wasm/provider.go
The checks in default block meant they were evaluated every time and causing high CPU usage.
- The client check has been changed to check after every 2 minutes similar to evm chains.
- The fetching block query has been changed to work in sync with subscription clients which will run if new subscription is started. This is similar to earlier as startheight only updates after client subscription changes which triggers pollHeightticker which updates start height.pollheightticker has been reduced by 1 sec to make sure it runs before the subscription.
=> fix: removed default executing conditions with proper condition

relayer/chains/wasm/events.go, relayer/chains/wasm/keys.go, relayer/chains/wasm/provider.go, relayer/chains/wasm/types/types.go
Wasm looks like removed the logs key and is empty.
Now to fix this, events key is added on event data, this removes block of code that parses events manually.
=> fix: wasm empty logs key for events

relayer/chains/evm/listener.go
This pull request fixes an issue where the default read timeout was being used for websocket connections. The patch updates the timeout to 10 seconds for early detection.
=> fix: use healhcheck timeout of 10s for early detection

relayer/chains/wasm/events.go, relayer/chains/wasm/provider.go, relayer/chains/wasm/types/types.go
This pr fixes an issue where events are not being parsed correctly due to changed event response format.
It now uses standard wasm abci types.
=> fix: changed wasm event types

relayer/chains/evm/listener.go
This pull request adds logs for when the subscription context is done in the `listener.go` file. Additionally, it updates the error log level from `Error` to `Warn` for subscription errors.
=> add: logs for subsription ctx done

relayer/chain_runtime_test.go, relayer/chains/icon/provider.go, relayer/relay.go, relayer/types/types.go
The message cache was using object as key which was causing it to add duplicate packets when error occurred and packet was flushed from db to memory. 
The cache will now use string key(src,eventType and Sn) and added necessary checks to avoid adding duplicate packets to msg cache.
Also, updated test cases and issue causing the tcs to fail.
=> fix: used string as cache key and modified other required functions accordingly

CHANGELOG.md
This pull request adds a new section to the CHANGELOG.md file, documenting the changes made in version 1.5.1 of the project. The changes include improvements to RPC retries and exponential backoffs, adjustments to websocket healthcheck timeouts, early initiation of startup tasks, and various fixes related to WASM functionality.
=> add(doc): add changelogs

relayer/chains/evm/client.go, relayer/chains/evm/listener.go
currently we have no timeout while creating evm clients so in some problematic rpc providers, the process gets stuck,connection error occurs and sometimes neither success nor failure is logged for hours.
added timeout to request while creating clients and retry until a new client is connected in case of reconnection.
=> fix: added contextual timeout to requests creating clients in case of evm chains

relayer/chains/evm/listener.go
the issue was caused due to variable mixing and using wrong scored variables for checking
=> fix: fixed client creation loop stuck issue

Dockerfile, example/configs/sui.json, relayer/chains/sui/config.go, relayer/chains/sui/listener.go, relayer/chains/sui/provider.go, relayer/chains/sui/tx.go, test/chains/sui/remotenet.go, test/interchaintest/relayer/centralized/centralized_relayer.go
Previously relayer was tightly coupled wilth specific dapp related information like module name and so on. Also, a single dapp could only be configured in the relayer from the config. So, in this PR the following features have been implemented:
- Relayer does not need to know dapp specific information.
- Also multiple dapp could be added in the relayer from the config itself.
=> feat: decouple sui dapp

relayer/chains/evm/listener.go, relayer/chains/evm/route.go, relayer/chains/icon/event_parse.go, relayer/chains/icon/listener.go, relayer/chains/icon/route.go, relayer/chains/sui/listener.go, relayer/chains/sui/provider_test.go, relayer/chains/sui/tx.go, relayer/chains/wasm/provider.go
Currently, in ICON while event log detection message data is not displayed and even while routing messages the message data is displayed in base64 string. So, in this PR, message data is logged while event log detection and data is displayed in hex format while message routing. Also, in the event monitoring API, the height that we get is one unit above the actual height in which event is published. So, the correct height is calculated in this PR. And since the tx-hash that we get in the event is not the tx-hash of transaction in which this event was published, it has been removed from the log.
=> fix: add proper logs for event log detection and message routing in icon

relayer/chains/evm/listener.go, relayer/store/messageStore_test.go, relayer/types/types.go
Few issues are addressed here:
- For websocket errors, the client is not reset and when subscribing, since default context is passed the subscription waited for 4 hours in some cases to report failure and worked only after that. The error has been added to the client recon list and the context also has been modified to use the websocket timeout context.
- The route message have a default lastTry of 0 which is set to current time only after the routing is tried. For emit messages, it is first checked if it has already been submitted before and in this case where the connection is not working, the lastTry may not be set for long period of time enough for the cleaner thread to clean these pending requests. This has been fixed by having a default value of current time.
=> fix: conn reset packet cleaned

example/configs/sui.json, relayer/chains/sui/client.go, relayer/chains/sui/config.go, relayer/chains/sui/listener.go, relayer/chains/sui/provider.go, relayer/chains/sui/tx.go, relayer/socket/server.go, test/chains/sui/remotenet.go, test/interchaintest/relayer/centralized/centralized_relayer.go
Currently, we are fetching 100 transactions per page containing events from RPC at an interval of 3s. In this setting, we are facing the following issues:
1. The transaction received from the query is not yet included in the checkpoint.
2. Sometimes, we are also missing some events.
So, to reduce the probability of facing these issues, we can try the following setting:
1. Make the query interval configurable from the chain config to restart the relayer with the desired interval whenever required.
2. Set transactions per page while querying to 15.
This setting might increase the probability of transaction digests being included in the checkpoint and reduce the chances of missing events.
Also, currently, in the relayer, we are storing all the old and upgraded package ids of Xcall. Initially …
=> fix: sui enhancements

cmd/chains.go, cmd/config.go, cmd/db.go, cmd/start.go, relayer/provider/provider.go, relayer/relay.go, relayer/relay_test.go
added `cluster-mode` config in the relayer to indicate cluster mode setup and passed the params to providers as well as relayers.
=> feat: added cluster configs for relayer

cmd/config.go, relayer/chains/evm/provider.go, relayer/chains/icon/event_parse.go, relayer/chains/icon/events.go, relayer/chains/icon/listener.go, relayer/chains/icon/methods.go, relayer/chains/icon/provider.go, relayer/chains/icon/route.go, relayer/chains/icon/types/types.go, relayer/chains/mockchain/provider.go, relayer/chains/steller/provider.go, relayer/chains/sui/config.go, relayer/chains/sui/provider.go, relayer/chains/wasm/client.go, relayer/chains/wasm/config.go, relayer/chains/wasm/provider.go, relayer/events/eventTypes.go, relayer/provider/provider.go, relayer/relay.go, relayer/types/types.go
Added new aggragation contract listener with emitting events packet acknowledge.
For cluster mode, regular emitEvents are handled for registration in the aggregation contracts and then for packetAcknowledgement event, it queries the chain for the message in specific height and then acknowledges the message with signed bytes.
=> feat: initial event sign interaction

relayer/chains/solana/client.go, relayer/chains/solana/listener.go, relayer/chains/solana/provider_test.go, relayer/chains/solana/tx.go, relayer/chains/solana/types/types.go, relayer/types/types.go
When sending multiple transactions concurrently to the SOLANA chain, the contract had a bug of dirty reads of the `last_saved_req_id`(all proxy requests got the same last_saved_req_id) before the message was received which failed all the concurrent transactions except the first one. This PR includes the changes to be made on the relayer side to incorporate the changes made on the contract side to fix the bug. The solution was to create a proxy request account using src_nid, src_conn_sn, and the dst_conn_addr of the relayer.
=> fix: solana concurrency issue

relayer/chains/evm/route.go, relayer/chains/icon/route.go, relayer/chains/solana/tx.go, relayer/chains/steller/tx.go, relayer/chains/sui/tx.go, relayer/chains/wasm/provider.go
Currently, we have redundant logging in the chain's implementation and the relay core. Also, after the message routing error, it was returned to both the callback and route response simultaneously, resulting in duplicate error handling. So, these two issues have been fixed in this PR.
=> fix: properly handle callback error while message routing

relayer/chains/solana/listener.go, relayer/relay.go
There was nil pointer dereference error while executing Rollback in solana due to XcallSn being not set in the Message. This is fixed in this PR.
=> fix: wrong xcallsn

relayer/chains/solana/provider.go
Prevent panic by returning an error when the transaction hash is not a valid base64 signature.
=> fix: Handle non-base64 transaction hashes gracefully

relayer/chains/steller/provider.go
Change the balance conversion from an integer to a float64 to improve accuracy in balance calculations and prevent panic.
=> fix: convert balance string from int to float64

relayer/types/types.go
Adjust the calculation method to round floating-point values to three decimal places for improved precision in the output.
=> refactor: round floating decimals to three places in calculations

relayer/chains/solana/tx.go
In SOLANA while executing recv_message for REPLY case, the Xcall Program ID was required in instruction accounts but not sent from the relayer. This has been fixed in this PR.
```bash
```
```bash
```
=> fix: add xcall prog account in recv_message for reply

relayer/chains/wasm/keys.go
Ensure the SDK context is set prior to creating an account in the keystore. This change improves the reliability of the account creation process.
=> fix: set SDK context before account creation

relayer/chains/solana/client.go, relayer/chains/steller/sorobanclient/client.go
=> fix: check for tx error

Makefile
Correctly specify the directory for the CI process and remove the unnecessary section name for the release target.
=> fix: CI configuration issues in Makefile

.github/workflows/release.yml
Adjust the formatting of the Docker build argument for the relayer version in the release workflow.
=> fix: relayer version docker build argument formatting

.goreleaser.yaml
Eliminate the Darwin-specific build configurations from the Goreleaser YAML file to streamline the build process.
=> remove: Darwin builds from Goreleaser configuration

relayer/chains/evm/client.go, relayer/chains/evm/provider.go
=> fix: wait for tx confirmation in evm properly

relayer/chains/evm/provider.go, relayer/chains/evm/route.go
Currently the transactions in BNB smart chain are stucked in the mempool for long time. The issue might be due to the EIP-1559 gas pricing strategy that we used by default for all evm chains. Since base fee is zero, using legacy gas pricing might help.
```bash
```
```bash
```
=> fix: enable to use legacy fee for evm

relayer/chains/evm/query.go, relayer/chains/icon/provider.go, relayer/chains/solana/tx.go, relayer/chains/steller/tx.go, relayer/chains/sui/tx.go, relayer/chains/wasm/provider.go, relayer/relay.go
Currently in cluster relayer, messages are not checked before execution resulting to duplicate execution and failures.
```bash
```
```bash
```
=> fix: check message receipt before execution for cluster

relayer/chains/icon/provider.go, relayer/chains/icon/route.go
Currently in icon if txn fails while estimating steps, no any debugging information is returned in the response. So, it is better to continue with default steps and execute txn so that the cause of failure can be known.
```bash
```
```bash
```
=> fix: use default step if estimation fails
