icon-project/centralized-relay

- cmd/db.go
- relayer/chain_runtime.go
- relayer/chain_runtime_test.go
- relayer/chains/evm/provider_test.go
- relayer/chains/evm/route.go
- relayer/chains/icon/event_parser.go
- relayer/chains/icon/listener.go
- relayer/chains/icon/provider_test.go
- relayer/chains/icon/route.go
- relayer/chains/mockchain/provider.go
- relayer/relay.go
- relayer/relay_test.go
- relayer/store/messageStore.go
- relayer/types/types.go
Fixes: message parse and missing src field
Fixes: cache key for message cache
Removes: time field on block cache
Refactor: better log message
> fix: missing src on emitMessage parse and fix: db message cache key pointer

- cmd/db.go
- docs/db.md
- relayer/chains/evm/client.go
- relayer/chains/evm/provider.go
- relayer/chains/icon/provider.go
- relayer/provider/provider.go
- relayer/socket/client.go
- relayer/socket/server.go
- relayer/socket/types.go
Ability revert message from relayer cmd
> feat: revert cmd for revertMessage

- CHANGELOG.md
- docs/config.md
- docs/contract.md
- docs/db.md
- example/configs/cosmos.json
- example/configs/evm.json
- example/configs/icon.json
Includes changes for version 1.2.0
add: contract cmd docs
add: new config update
add: migration guides from 1.0.0 to 1.2.0
rf: refactor doc from suggestions.
> wip: Docs update

- .github/workflows/release.yml
- Makefile
- README.md
Upgrade go version to 1.22 from 1.19 for CI.
> fix(workflow): go version

- relayer/chains/evm/route.go
Fixes double nonce increments when fixing nonce error
> fix: avoid double nonce increment

- CHANGELOG.md
- relayer/chains/evm/provider.go
- relayer/chains/evm/route.go
- relayer/chains/icon/provider.go
- relayer/chains/icon/route.go
This pull request updates the gas adjustment and step adjustment in the config file. The gas adjustment is changed from `gas-buffer` to `gas-adjustment`, and the step adjustment is changed from `step-buffer` to `step-adjustment`. These changes ensure that the gas and step limits are adjusted correctly when sending transactions.
> rf: gas adjustment and step adjustment in config

- test/chains/sui/remotenet.go
- test/e2e/tests/xcall.go
- test/interchaintest/relayer/centralized/centralized_relayer.go
updated e2e test as per latest changes in sui contracts and relayer
> feat: e2e sui updates

- relayer/chains/evm/provider.go
This pull request increases the suggested gas price by 10% in order to account for changes in the gas market.
> rf: increase suggested gas price by 10%

- relayer/chains/evm/provider.go
- relayer/chains/evm/route.go
This pull request increases the suggested gas price by 15% in the `GetTransationOpts` function of the `Provider` struct. This change ensures that the gas price used for transactions is adjusted to reflect current market conditions.
> rf: increase suggested gas price by 15%

- relayer/chains/evm/listener.go
- relayer/chains/wasm/provider.go
This pull request fixes the RPC recovery process by replacing recursion with a ticker. The `Listener` function now uses a ticker to control the timing of certain operations, such as subscribing to new blocks and polling for the latest block height. Additionally, a `resetFunc` is introduced to handle errors and reset the ticker when necessary. This improves the reliability and efficiency of the RPC recovery process.
> refactor: RPC recovery using ticker

- relayer/relay.go
This pr removes the concurrrency that happens with multiple messages
> rm: concurrency

- test/chains/chain.go
- test/chains/cosmos/localnet.go
- test/chains/evm/localnet.go
- test/chains/icon/localnet.go
- test/chains/sui/remotenet.go
- test/e2e/tests/xcall.go
- test/interchaintest/relayer/centralized/centralized_relayer.go
Changed e2e to accomodate for auto rollback for SUI chain and config changes
> fix: updated to reflecct changes on sui modules and relayer config

- CHANGELOG.md
This pull request adds a new version changelog to the project. The changelog includes fixes for WS connection recovery for the evm chain and proper error checking for the icon and cosmos chain. It also includes a polling fix for evm when ws errors and the addition of gas price cap and gas tip for the evm chain.
> "Add new version changelog"

- docs/config.md
- example/configs/cosmos.json
- example/configs/evm.json
- example/configs/icon.json
- example/configs/injective.json
This pull request updates the chain configurations in the `config.md` file and the example configuration files. It includes the following changes:
- Added a new chain configuration for `injective`
- Updated the `disabled` property for the `icon` and `cosmos` chains
- Added new properties `gas-adjustment` and `extra-codecs` for the `cosmos` chain
- Removed the `concurrency` property from the `evm` chain configuration
> doc: Update chain configurations

- relayer/chains/wasm/config.go
- relayer/chains/wasm/provider.go
- relayer/chains/wasm/types/types.go
this pr diables batch query when there is single block to sync.
fixes: #301
> feat: disable batch query conditionally

- relayer/chains/wasm/provider.go
This pull request refactors the block message fetching process to improve performance. Previously, the code sent a request for every single file, resulting in unnecessary overhead. This PR ensures that only one request is sent when fetching block messages, significantly reducing the number of requests and improving overall performance.
> refactor: remove concurrency for wasm when fetching blocks.

- Dockerfile
- Makefile
upgraded cosmwasm version and added tags similar to config in go release for arm configs
> fix: fixed issue with docker build for amr linux

- relayer/chains/evm/abi/cluster_conn.go
- relayer/chains/evm/client.go
- relayer/chains/evm/provider.go
- relayer/chains/evm/route.go
- relayer/chains/icon/event_parse.go
- relayer/chains/icon/events.go
- relayer/chains/icon/methods.go
- relayer/chains/icon/provider.go
- relayer/chains/icon/route.go
- relayer/chains/icon/types/types.go
- relayer/chains/mockchain/provider.go
- relayer/chains/steller/provider.go
- relayer/chains/sui/config.go
- relayer/chains/wasm/config.go
- relayer/events/eventTypes.go
- relayer/provider/provider.go
- relayer/relay.go
- relayer/types/types.go
Added event handling and parsing for transmitReady event
Added logic to fetch signatures for an event form the aggregation contract
Added dummy cluster conn abi for evm clients
Only handled final message passing for evm and icon chains.
> feat: added logic for parsing and acting on transmitReadyEvent

- relayer/chains/steller/tx.go
- relayer/relay.go
Callback error after message route was not handled properly. This PR solves that issue in the STELLAR chain.
> fix: stellar handle error properly

- cmd/config.go
- cmd/keystore.go
- relayer/chains/icon/event_parse.go
- relayer/chains/wasm/provider.go
- relayer/chains/wasm/types/msg.go
> fix: msg signing and receive cluster message in cosmwasm

- relayer/chains/solana/listener.go
> fix: start event query from recent xcall tx signature by default

- relayer/chains/sui/listener.go
> fix: start querying from latest xcall tx digest by default

- relayer/chains/steller/client.go
- relayer/chains/steller/listener.go
- relayer/chains/steller/provider.go
- relayer/chains/steller/sorobanclient/client.go
- relayer/chains/steller/sorobanclient/types.go
- relayer/chains/steller/tx.go
- relayer/chains/steller/types/types.go
Replaced horizon client with soroban client for getting transaction events and submitting transaction in to the stellar network
```bash
```
> feat: Fix issues due to stellar update

- relayer/chains/steller/listener.go
- relayer/chains/steller/provider.go
The error was only logged but not returned causing issue when trying to manual relay older or wrong transaction.
```bash
```
```bash
```
> fix: added missing error handling in case of error while fetching txn

- test/chains/solana/remotenet.go
- test/interchaintest/relayer/centralized/centralized_relayer.go
Fixed e2e test cases for solana chain
```bash
```
```bash
```
> fix: fixed e2e for solana

- relayer/chains/solana/client.go
- relayer/chains/solana/listener.go
- relayer/chains/solana/provider.go
> fix: handle tx error after getting txn

- relayer/chains/steller/sorobanclient/client.go
Added status check for failed to stop excessive polling
```bash
```
```bash
```
> fix: fixed checking for status

- relayer/chains/solana/listener.go
- relayer/chains/solana/tx.go
- relayer/types/types.go
> fix: add logs for solana tx & reduce retry & implement context timeout

- .github/workflows/release.yml
Update ref_name in release.yml
```bash
```
```bash
```
> Update ref_name in release.yml

- .github/workflows/release.yml
Correctly specify the directory in the CI configuration to ensure proper execution of the build process.
> fix: docker build context directory selection

- relayer/chains/solana/listener.go
- relayer/chains/solana/tx.go
- utils/sorter/sort_test.go
> fix: redundant tx solana

- relayer/chains/solana/listener.go
> fix: incorrect tx filter in solana

- relayer/chains/steller/tx.go
- relayer/chains/steller/types/msg.go
> feat: implement cluster connection recv_message in stellar

- relayer/chains/evm/query.go
- relayer/chains/icon/provider.go
- relayer/chains/mockchain/provider.go
- relayer/chains/solana/listener.go
- relayer/chains/solana/tx.go
- relayer/chains/steller/tx.go
- relayer/chains/sui/tx.go
- relayer/chains/wasm/provider.go
- relayer/provider/provider.go
- relayer/relay.go
- relayer/socket/server.go
> fix: solana multiple call

- relayer/chains/solana/config.go
> fix: add missing common config in solana

- relayer/chains/solana/tx.go
- relayer/chains/sui/provider.go
- relayer/chains/sui/tx.go
> feat: sui solana cluster connection

- relayer/chains/evm/route.go
> fix: use gas limit from config

- relayer/chains/evm/client.go
- relayer/chains/evm/provider.go
- relayer/chains/evm/route.go
- relayer/chains/evm/types/types.go
> fix: eth nonce issue

- relayer/chains/evm/route.go
> fix: mutex unlock

- relayer/chains/solana/config.go
- relayer/chains/solana/tx.go
> fix: check for priority fee limit

- relayer/chains/wasm/client.go
- relayer/chains/wasm/config.go
> fix: remove grpc url

- relayer/chains/evm/query.go
- relayer/chains/icon/provider.go
- relayer/chains/solana/tx.go
- relayer/chains/steller/tx.go
- relayer/chains/sui/tx.go
- relayer/chains/wasm/provider.go
- relayer/relay.go
> fix: check message receipt

- relayer/relay.go
> fix: add additional enabled check

- relayer/chains/sui/tx.go
> fix: pick smallest coin for execute params

- go.mod
- go.sum
- relayer/chains/solana/client.go
- relayer/chains/solana/listener.go
> fix: retry solana tx

- relayer/chains/solana/provider.go
- relayer/relay.go
> fix: ignore invalid event log

- relayer/relay.go
> fix: proper error check and return

- relayer/chains/evm/provider.go
- relayer/chains/evm/route.go
> fix: cfg overrides gas limit

- relayer/chains/solana/listener.go
- relayer/chains/solana/tx.go
- relayer/chains/solana/types/types.go
> fix: make changes for solana intent

- relayer/chains/solana/client.go
> fix: use avg priority fee for solana tx
